### ISSUE TITLE
Nvidia Video SDK install on ArchLinux places headers outside cuda install

### ISSUE THREAD

**Issue by FallingSnow** [ViliamVadocz/nvidia-video-codec-sdk#13]
[nvidia-sdk](https://aur.archlinux.org/packages/nvidia-sdk) on arch linux's AUR installs the headers to `/usr/include/nvidia-sdk`. However the cuda is installed to `/opt/cuda`.

Is it possible we could get another variable for the nvidia video SDK considering it is a separate install?

**Comment by ViliamVadocz** [comment]
Yes. I will be able to work on this in a few days. If you would like this to be done sooner feel free to make a pull request and I will happily review it.

**Comment by FallingSnow** [comment]
I'm not in any rush, I just copied the headers for now.

**Comment by ViliamVadocz** [comment]
@FallingSnow 
Let me know if the master branch is working for you now. https://github.com/ViliamVadocz/nvidia-video-codec-sdk/commit/a01c07cdbb16e7571beb85c98cd63792d9dec01b added `/usr/include/nvidia-sdk` to the candidate paths and the build script is no longer assumes the same installation location as CUDA.

If you report back that it is working, I will publish the new version as `0.1.2`.

**Comment by FallingSnow** [comment]
I had to use this on windows as that was the default install path. `$env:CUDA_ROOT="C:/Program Files/NVIDIA GPU Computing Toolkit/Cuda/v12.2"`

Let me test the linux change you just made.

**Comment by FallingSnow** [comment]
Linux changes fixed the issue. Thank you!

Would you like me to open another issue about the Windows install location?

**Comment by ViliamVadocz** [comment]
> Would you like me to open another issue about the Windows install location?

You may. I think I need more information about what errors you are getting because right now I am somewhat confused. Specifically, you said you set `CUDA_PATH` which makes me think this is a `cudarc` issue.

**Comment by FallingSnow** [comment]
I'm unsure if it's a cudarc issue but the build couldn't find the headers on a fresh cuda install. I figured this was because `build.rs` looks at `C:/Program Files/NVIDIA GPU Computing Toolkit` instead of `C:/Program Files/NVIDIA GPU Computing Toolkit/Cuda/v12.2`.

**Comment by ViliamVadocz** [comment]
@FallingSnow Yes that's correct, but that is a `cudarc` issue, since this library does not actually look for CUDA anymore (cudarc, which is a dependency, needs it though).

**Comment by FallingSnow** [comment]
Ah, after rereading `build.rs` I see what you're saying. You only look for Video SDK headers. Yeah, this must be a cudarc issue then. Thanks for pointing that out.
